name: ci

on:
  push:
  schedule:
    - cron: '0 22 * * *'   # 06:00 Asia/Taipei (UTC+8)

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Run pipeline (sample data)
        run: |
          source .venv/bin/activate
          python src/pipeline.py --date 2025-09-15
      - name: Upload outputs
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
